from __future__ import annotations

LABEL_LAYOUTS = {
    "a4_3x8_63_5x33_9": {
        "label_de": "A4 Etiketten 24 (3×8, 63,5×33,9 mm · Avery/Zweckform kompatibel)",
        "label_en": "A4 labels 24 (3×8, 63.5×33.9 mm · Avery/Zweckform compatible)",
        "columns": 3,
        "cell_w_mm": 63.5,
        "cell_h_mm": 33.9,
    },
    "a4_3x7_63_5x38_1": {
        "label_de": "A4 Etiketten 21 (3×7, 63,5×38,1 mm · Avery L7160)",
        "label_en": "A4 labels 21 (3×7, 63.5×38.1 mm · Avery L7160)",
        "columns": 3,
        "cell_w_mm": 63.5,
        "cell_h_mm": 38.1,
    },
    "a4_2x8_99_1x33_9": {
        "label_de": "A4 Etiketten 16 (2×8, 99,1×33,9 mm · Avery L7162)",
        "label_en": "A4 labels 16 (2×8, 99.1×33.9 mm · Avery L7162)",
        "columns": 2,
        "cell_w_mm": 99.1,
        "cell_h_mm": 33.9,
    },
    "a4_2x7_99_1x38_1": {
        "label_de": "A4 Etiketten 14 (2×7, 99,1×38,1 mm · Avery L7163)",
        "label_en": "A4 labels 14 (2×7, 99.1×38.1 mm · Avery L7163)",
        "columns": 2,
        "cell_w_mm": 99.1,
        "cell_h_mm": 38.1,
    },
    "a4_2x4_99_1x67_7": {
        "label_de": "A4 Etiketten 8 (2×4, 99,1×67,7 mm · Avery L7165)",
        "label_en": "A4 labels 8 (2×4, 99.1×67.7 mm · Avery L7165)",
        "columns": 2,
        "cell_w_mm": 99.1,
        "cell_h_mm": 67.7,
    },
    "a4_1x10_189_9x25_4": {
        "label_de": "A4 Etiketten 10 (1×10, 189,9×25,4 mm · Avery L7651)",
        "label_en": "A4 labels 10 (1×10, 189.9×25.4 mm · Avery L7651)",
        "columns": 1,
        "cell_w_mm": 189.9,
        "cell_h_mm": 25.4,
    },
    "a4_2x2_105x74_25": {
        "label_de": "A4 Etiketten 4 (2×2, 105×74,25 mm)",
        "label_en": "A4 labels 4 (2×2, 105×74.25 mm)",
        "columns": 2,
        "cell_w_mm": 105.0,
        "cell_h_mm": 74.25,
    },
    "a4_4x12_48_5x25_4": {
        "label_de": "A4 Etiketten 48 (4×12, 48,5×25,4 mm)",
        "label_en": "A4 labels 48 (4×12, 48.5×25.4 mm)",
        "columns": 4,
        "cell_w_mm": 48.5,
        "cell_h_mm": 25.4,
    },
    "a4_4x16_48_5x16_9": {
        "label_de": "A4 Etiketten 64 (4×16, 48,5×16,9 mm · Avery L4732)",
        "label_en": "A4 labels 64 (4×16, 48.5×16.9 mm · Avery L4732)",
        "columns": 4,
        "cell_w_mm": 48.5,
        "cell_h_mm": 16.9,
    },
    "a4_cards_2x5": {
        "label_de": "A4 Karten (2 Spalten, flexibel)",
        "label_en": "A4 cards (2 columns, flexible)",
        "columns": 2,
        "cell_w_mm": 99.0,
        "cell_h_mm": 52.0,
    },
    "a4_full_page": {
        "label_de": "A4 Vollseite (1 Etikett · Avery J8167)",
        "label_en": "A4 full page (1 label · Avery J8167)",
        "columns": 1,
        "cell_w_mm": 190.0,
        "cell_h_mm": 277.0,
    },
}



TRANSLATIONS = {
    "de": {
        "app_title": "Filament Datenbank",
        "app_subtitle": "Deine Filamentspulen im Blick",
        "footer_text": "Lokale Filament-Verwaltung",
        "stats_title": "Statistiken",
        "stat_total_spools": "Spulen gesamt",
        "stat_total_weight": "Gesamtgewicht",
        "stat_total_remaining": "Restmenge",
        "stat_total_value": "Warenwert",
        "stat_empty_spools": "Leere Spulen",
        "stat_low_stock_spools": "Niedriger Bestand",
        "kpi_month_usage": "Monatsverbrauch",
        "kpi_month_cost": "Kosten (Monat)",
        "kpi_usage_trend": "Verbrauch pro Monat",
        "kpi_cost_trend": "Kosten pro Monat",
        "kpi_top_material_trend": "Top-Material je Monat",
        "kpi_top_color_trend": "Top-Farbe je Monat",
        "kpi_last_months": "letzte 6 Monate",
        "kpi_no_usage_data": "Keine Verbrauchsdaten vorhanden.",
        "top5_materials": "Top 5 Materialien",
        "top5_colors": "Top 5 Farben",
        "top5_remaining_share": "Anteil Restmenge",
        "settings": "Einstellungen",
        "nav_booking": "Buchung",
        "nav_tracking": "Tracking",
        "nav_slot_status": "Slotstatus",
        "nav_printers": "Drucker",
        "nav_storage_locations": "Lagerorte",
        "nav_supplies": "Verbrauchsmaterial",
        "nav_menu": "Menü",
        "nav_home": "Dashboard",
        "settings_language": "Sprache",
        "settings_theme": "Theme",
        "settings_project": "Projekt",
        "settings_privacy_blur": "Datenschutz-Blur",
        "settings_privacy_blur_enable": "Blur aktivieren",
        "settings_privacy_blur_disable": "Blur deaktivieren",
        "live_updated": "Live aktualisiert",
        "live_updated_now": "gerade eben",
        "settings_auto_refresh": "Auto-Aktualisierung",
        "auto_refresh_off": "Aus",
        "auto_refresh_5s": "5 Sekunden",
        "auto_refresh_10s": "10 Sekunden",
        "auto_refresh_30s": "30 Sekunden",
        "project_private": "Privat",
        "project_business": "Geschäftlich",
        "theme_light": "Hell",
        "theme_dark": "Dunkel",
        "theme_system": "System",
        "landing_title": "Willkommen bei der Filament Datenbank",
        "landing_subtitle": "Verwalte Bestand, Lagerorte und Verbrauch zentral.",
        "landing_auth_hint": "Die Authentifizierung ist vorbereitet und kann im nächsten Schritt mit echter Benutzerverwaltung verbunden werden.",
        "landing_cta_login": "Anmelden",
        "landing_cta_register": "Registrieren",
        "landing_cta_dashboard": "Zum Dashboard",
        "auth_email": "E-Mail",
        "auth_password": "Passwort",
        "auth_name": "Name",
        "login_title": "Anmeldung",
        "login_hint": "Melde dich mit deinem Konto an.",
        "register_title": "Registrierung",
        "register_hint": "Erstelle ein neues Konto.",
        "auth_submit_login": "Anmelden",
        "auth_submit_register": "Konto erstellen",
        "auth_coming_soon": "Authentifizierung ist vorbereitet. Backend-Anbindung folgt im nächsten Schritt.",
        "auth_logout": "Abmelden",
        "auth_login_success": "Erfolgreich angemeldet.",
        "auth_register_success": "Konto erstellt und angemeldet.",
        "auth_invalid_credentials": "Ungültige E-Mail oder Passwort.",
        "auth_email_exists": "Diese E-Mail ist bereits registriert.",
        "auth_password_too_short": "Passwort muss mindestens 8 Zeichen haben.",
        "auth_required": "Bitte zuerst anmelden.",
        "quick_actions": "Schnellzugriff",
        "data_section": "Daten",
        "backup_restore": "Backup / Restore",
        "analysis_tab": "Analyse",
        "audit_tab": "Audit-Log",
        "thresholds_tab": "Schwellenwerte",
        "analysis_title": "Analyse",
        "audit_title": "Audit-Log",
        "thresholds_title": "Schwellenwerte",
        "thresholds_hint": "Übersicht aller gesetzten Low-Stock-Schwellenwerte.",
        "thresholds_material_defaults": "Material-Standardschwellen",
        "thresholds_spool_overrides": "Spulen-spezifische Schwellen",
        "thresholds_none_material": "Keine Material-Schwellenwerte gesetzt.",
        "thresholds_none_spool": "Keine Spulen-Schwellenwerte gesetzt.",
        "analysis_hint": "Bestände gruppiert nach Marke, Material, Farbe und Lagerort.",
        "analysis_by_brand": "Nach Marke",
        "analysis_by_material": "Nach Material",
        "analysis_by_color": "Nach Farbe",
        "analysis_by_location": "Nach Lagerort",
        "analysis_count": "Anzahl",
        "analysis_share": "Anteil Restmenge",
        "analysis_period_days": "Zeitraum (Tage)",
        "analysis_trend_months": "Trend (Monate)",
        "analysis_apply_filters": "Filter anwenden",
        "analysis_kpi_usage_period": "Verbrauch im Zeitraum",
        "analysis_kpi_cost_period": "Kosten im Zeitraum",
        "analysis_kpi_low_stock_count": "Niedrigbestand (aktuell)",
        "analysis_kpi_top_material_usage": "Top-Verbrauch Material",
        "analysis_kpi_top_color_usage": "Top-Verbrauch Farbe",
        "analysis_kpi_printer_slot_usage": "Verbrauch pro Drucker/Slot",
        "analysis_chart_usage_cost": "Verbrauch & Kosten im Trend",
        "analysis_low_stock_items": "Kritische Spulen",
        "analysis_no_data": "Keine Daten im gewählten Zeitraum.",
        "audit_hint": "Revisionssichere Historie kritischer Aktionen (wer/was/wann).",
        "audit_action": "Aktion",
        "audit_period_days": "Zeitraum (Tage)",
        "audit_actor": "Akteur",
        "audit_entity": "Objekt",
        "audit_details": "Details",
        "audit_all_actions": "Alle Aktionen",
        "audit_no_data": "Keine Audit-Einträge im gewählten Zeitraum.",
        "add_spool": "Neue Spule",
        "import_data": "Import",
        "import_export": "Import / Export",
        "export_csv": "CSV exportieren",
        "export_excel": "Excel exportieren",
        "spool_list": "Spulenliste",
        "search_placeholder": "Suchen nach Marke, Material, Farbe, Lagerort",
        "hide_empty_spools": "Leere Spulen ausblenden",
        "rows_per_page": "Zeilen pro Seite",
        "entries_label": "Einträge",
        "page_label": "Seite",
        "prev_page": "Zurück",
        "next_page": "Weiter",
        "all_colors": "Alle Farben",
        "search": "Suchen",
        "spool_index": "Index",
        "brand": "Marke",
        "material": "Material",
        "color": "Farbe",
        "bulk_add": "Mehrfach hinzufügen",
        "bulk_add_hint": "Mehrere Spulen in einem Schritt anlegen.",
        "add_row": "Zeile hinzufügen",
        "save_all": "Alle speichern",
        "quantity": "Anzahl",
        "quantity_hint": "Erstellt mehrere identische Spulen.",
        "manage_presets": "Vorgaben verwalten",
        "presets_title": "Vorgaben",
        "add_brand": "Hersteller hinzufügen",
        "add_material": "Material hinzufügen",
        "add_color": "Farbe hinzufügen",
        "add_color_map": "Farben zuweisen",
        "presets_basic_title": "Grunddaten hinzufügen",
        "presets_basic_hint": "Hersteller, Material oder Farben schnell ergänzen.",
        "assign_colors_title": "Farben zuordnen",
        "assign_colors_hint": "Wähle Hersteller und Material, dann Farben (kommagetrennt).",
        "import_colors": "Farben importieren",
        "import_colors_hint": "CSV/Excel mit Spalten: brand, material, color",
        "select_brand": "Hersteller wählen",
        "select_material": "Material wählen",
        "colors_list": "Farben (kommagetrennt)",
        "brand_hint": "Mehrere Hersteller mit Komma trennen",
        "material_hint": "Mehrere Materialien mit Komma trennen",
        "color_hint": "Mehrere Farben mit Komma trennen",
        "material_group": "Materialgruppe",
        "weight": "Gewicht",
        "remaining": "Restmenge",
        "threshold": "Schwelle",
        "price": "Preis",
        "location": "Lagerort",
        "storage_location": "Strukturierter Lagerort",
        "storage_location_none": "Kein strukturierter Lagerort",
        "storage_locations_title": "Lagerorte",
        "storage_locations_hint": "Verwalte Lagerbereiche und Fächer (z. B. REGAL1/FACH_A).",
        "storage_locations_add": "Lagerort hinzufügen",
        "storage_area_code": "Bereichscode",
        "storage_area_name": "Bereichsname",
        "storage_sub_code": "Fachcode",
        "storage_sub_name": "Fachname",
        "storage_path": "Pfad",
        "storage_usage": "Belegte Spulen",
        "storage_delete": "Lagerort löschen",
        "storage_none": "Keine Lagerorte vorhanden.",
        "storage_invalid_code": "Ungültiger Code. Erlaubt: Buchstaben/Zahlen sowie - und _.",
        "storage_location_exists": "Dieser Lagerort existiert bereits.",
        "storage_location_saved": "Lagerort wurde gespeichert.",
        "storage_location_deleted": "Lagerort wurde gelöscht.",
        "storage_location_in_use": "Lagerort ist noch Spulen zugewiesen und kann nicht gelöscht werden.",
        "storage_location_invalid": "Ausgewählter Lagerort ist ungültig.",
        "storage_filter": "Lagerort-Filter",
        "storage_filter_all": "Alle Lagerorte",
        "supplies_title": "Verbrauchsmaterial",
        "supplies_hint": "Einfacher Bestand für Verbrauchsmaterial wie Kleber, Düsen oder Reinigungsmittel.",
        "supplies_add": "Eintrag hinzufügen",
        "supplies_category_add": "Kategorie hinzufügen",
        "supplies_category_exists": "Kategorie existiert bereits.",
        "supplies_category_saved": "Kategorie wurde gespeichert.",
        "supplies_name": "Name",
        "supplies_category": "Kategorie",
        "supplies_quantity": "Menge",
        "supplies_unit": "Einheit",
        "supplies_min_quantity": "Mindestbestand",
        "supplies_notes": "Notiz",
        "supplies_adjust": "Zu-/Abbuchung",
        "supplies_adjust_hint": "Wert mit + oder - eingeben, z. B. -1 oder +2.",
        "supplies_none": "Noch kein Verbrauchsmaterial erfasst.",
        "supplies_category_none": "Keine Kategorie",
        "supplies_saved": "Eintrag wurde gespeichert.",
        "supplies_updated": "Eintrag wurde aktualisiert.",
        "supplies_deleted": "Eintrag wurde gelöscht.",
        "supplies_adjusted": "Bestand wurde angepasst.",
        "supplies_invalid": "Bitte einen Namen und eine gültige Menge angeben.",
        "supplies_invalid_adjust": "Bitte eine gültige Zu-/Abbuchung angeben.",
        "supplies_default_category": "Verbrauchsmaterial",
        "supplies_default_unit": "Stk",
        "ams_printer": "AMS Drucker",
        "ams_slot": "AMS Slot",
        "status": "Status",
        "lifecycle_status": "Lebenszyklus",
        "lifecycle_filter_all": "Alle Lebenszyklus-Status",
        "lifecycle_new": "Neu",
        "lifecycle_opened": "Geöffnet",
        "lifecycle_dry_stored": "Trocken gelagert",
        "lifecycle_humidity_risk": "Feuchterisiko",
        "lifecycle_drying": "Wird getrocknet",
        "lifecycle_brittle": "Spröde",
        "lifecycle_empty": "Leer",
        "lifecycle_recycled": "Recycelt",
        "lifecycle_archived": "Archiviert",
        "actions": "Aktionen",
        "in_use": "In Nutzung",
        "empty": "Leer",
        "low_stock": "Niedrig",
        "idle": "Inaktiv",
        "threshold_source_spool": "Spule",
        "threshold_source_material": "Material",
        "threshold_none": "-",
        "low_stock_threshold": "Low-Stock Schwelle",
        "material_thresholds_title": "Material-Schwellwerte",
        "material_thresholds_hint": "Standard-Schwellwert pro Spule nach Material in Gramm.",
        "material_total_threshold": "Material-Gesamtschwelle",
        "material_total_thresholds_title": "Material-Gesamtschwellen",
        "material_total_thresholds_hint": "Schwellwert auf Gesamtbestand pro Material in Gramm.",
        "reorder_list_title": "Nachbestellung erforderlich",
        "reorder_none": "Aktuell keine Nachbestellung nötig.",
        "reorder_missing": "Fehlmenge",
        "reorder_min_order": "Mindestmenge",
        "reorder_critical_only": "Nur kritische Einträge",
        "reorder_show_all": "Alle Einträge anzeigen",
        "reorder_needed": "Nachbestellen",
        "reorder_ok": "OK",
        "forecast_card_30": "Bestandsreichweite (30 Tage Verbrauch)",
        "forecast_card_90": "Bestandsreichweite (90 Tage Verbrauch)",
        "forecast_days": "Tage",
        "forecast_daily_usage": "Ø Verbrauch/Tag",
        "forecast_no_data": "Keine Verbrauchsdaten",
        "import_profile_use": "Import-Mapping-Profil verwenden",
        "import_profile_none": "Kein Profil",
        "import_profile_save_as": "Mapping als Profil speichern",
        "import_map_brand": "Spalte für Marke",
        "import_map_material": "Spalte für Material",
        "import_map_color": "Spalte für Farbe",
        "import_map_weight": "Spalte für Gewicht (g)",
        "import_map_remaining": "Spalte für Restmenge (g)",
        "import_map_threshold": "Spalte für Low-Stock Schwelle",
        "import_map_price": "Spalte für Preis",
        "import_map_location": "Spalte für Lagerort",
        "toggle_use": "Toggle",
        "edit": "Bearbeiten",
        "delete": "Löschen",
        "qr": "QR",
        "confirm_delete": "Spule wirklich löschen?",
        "no_spools": "Keine Spulen vorhanden.",
        "save": "Speichern",
        "cancel": "Abbrechen",
        "usage_upload": "Buchung",
        "booking_area_title": "Buchung",
        "booking_section_book": "Buchen",
        "booking_section_tracking": "Tracking",
        "usage_hint": "Lade eine 3MF-Datei hoch. Falls Gramm nicht erkannt werden, gib sie manuell an.",
        "select_spools": "Spulen auswählen",
        "upload_3mf": "3MF-Datei",
        "manual_grams": "Manuelle Grammangabe",
        "manual_grams_hint": "Nur nötig, wenn die 3MF keine Grammangabe enthält.",
        "usage_no_grams": "In der 3MF wurde keine Grammangabe gefunden. Bitte manuell eingeben.",
        "usage_no_grams_bambu_unsliced": "In dieser Bambu-3MF sind keine Verbrauchsdaten enthalten (wahrscheinlich nicht gesliced). Bitte in Bambu Studio slicen und erneut speichern oder manuell eintragen.",
        "usage_no_match": "Keine passende Spule automatisch gefunden. Bitte manuell auswählen.",
        "usage_breakdown": "Erkannter Materialverbrauch",
        "usage_total": "Gesamt",
        "usage_total_length": "Gesamtlänge",
        "usage_filament_switches": "Filamentwechsel",
        "usage_estimated_cost": "Kosten",
        "usage_advanced_title": "Erweiterte Bambu-Statistik",
        "usage_history_title": "Verbrauchs-Historie",
        "usage_history_when": "Wann",
        "usage_history_who": "Wer",
        "usage_history_slicer": "Slicer",
        "usage_history_mode": "Modus",
        "usage_mode_auto": "Automatisch",
        "usage_mode_manual": "Manuell",
        "usage_mode_auto_slicer": "Automatisch (Slicer)",
        "usage_mode_auto_bambu": "Automatisch (Bambu Studio)",
        "usage_mode_upload_manual": "Datei-Upload (manuell)",
        "usage_mode_manual_entry": "Manuelle Eingabe",
        "usage_history_file": "3MF-Datei",
        "usage_history_spool": "Spule",
        "usage_history_spools": "Spulen",
        "usage_history_breakdown": "Aufteilung",
        "usage_history_spool_id": "Spulen-Index",
        "usage_history_amount": "Abzug",
        "usage_history_printer": "Drucker",
        "usage_history_ams_slots": "AMS-Slots",
        "ams_slot_conflict": "AMS Slot-Konflikt: Dieser Slot ist bereits einer anderen Spule zugeordnet.",
        "slot_status_title": "Soll/Ist Slotstatus",
        "slot_status_hint": "Vergleich zwischen gepflegter Spulenzuordnung und zuletzt gepolltem Gerätestatus.",
        "slot_status_printer": "Drucker",
        "slot_status_slot": "Slot",
        "slot_status_ams": "AMS",
        "slot_status_expected": "Soll (Spule)",
        "slot_status_observed": "Ist (Live)",
        "slot_status_state": "Status",
        "slot_status_seen": "Zuletzt gesehen",
        "slot_status_source": "Quelle",
        "slot_state_ok": "OK",
        "slot_state_mismatch": "Abweichung",
        "slot_state_missing": "Fehlt",
        "slot_state_stale": "Veraltet",
        "slot_state_unknown": "Unbekannt",
        "slot_status_no_mapped": "Keine gemappten Slots vorhanden.",
        "slot_status_no_live": "Keine Live-Slotdaten vorhanden.",
        "slot_data_health": "Live-Datenstatus",
        "slot_data_fresh": "Aktuell",
        "slot_data_stale": "Veraltet",
        "slot_data_no_data": "Keine Live-Daten",
        "slot_data_age": "Alter",
        "slot_remap_action": "AMS-Mapping aus Live-Daten korrigieren",
        "slot_remap_done": "AMS-Mapping aktualisiert: {updated} Spule(n).",
        "slot_remap_none": "Keine eindeutigen Korrekturen gefunden.",
        "slot_remap_no_live": "Keine Live-Slotdaten vorhanden.",
        "slot_format_migrate_action": "Slot-Format auf 1xx/2xx migrieren",
        "slot_format_migrate_done": "Slot-Format migriert: Spulen={spools}, Live-Slots={states}, Verläufe={contexts}.",
        "slot_format_migrate_skip": "Einige Einträge wurden wegen Konflikten übersprungen: {count}.",
        "printers_title": "Druckerverwaltung",
        "printers_hint": "Verwalte mehrere Drucker und deren Live-Telemetrie zentral.",
        "printers_add": "Drucker hinzufügen",
        "printers_none": "Keine Drucker vorhanden.",
        "printer_name": "Name",
        "printer_serial": "Seriennummer",
        "printer_host": "Host/IP",
        "printer_port": "Port",
        "printer_access_code": "Access Code",
        "printer_ams_name_map": "AMS-Name",
        "printer_ams_name_map_hint": "z. B. HT-A",
        "printer_active": "Aktiv",
        "printer_status": "Status",
        "printer_last_seen": "Zuletzt gesehen",
        "printer_job": "Job",
        "printer_progress": "Fortschritt",
        "printer_temps": "Temperaturen",
        "printer_firmware": "Firmware",
        "printer_source": "Quelle",
        "printer_error": "Fehler",
        "printer_external_spool": "Externe Spule",
        "printer_external_spool_active": "Aktiv",
        "printer_external_spool_inactive": "Inaktiv",
        "printer_tab_device": "Druckerdaten",
        "printer_tab_ams": "AMS-Daten",
        "printer_ams_title": "AMS (Live-Slots)",
        "printer_ams_empty": "Keine AMS-Livedaten für diesen Drucker.",
        "printer_saved": "Drucker wurde gespeichert.",
        "printer_deleted": "Drucker wurde gelöscht.",
        "printer_invalid": "Bitte Name und Seriennummer angeben.",
        "printer_duplicate_serial": "Diese Seriennummer existiert bereits im Projekt.",
        "printer_duplicate_name": "Dieser Druckername existiert bereits im Projekt.",
        "printer_status_online": "Online",
        "printer_status_offline": "Offline",
        "printer_status_unknown": "Unbekannt",
        "usage_history_empty": "Noch keine Verbrauchseinträge vorhanden.",
        "usage_undo_last": "Letzte Abbuchung rückgängig",
        "usage_undo_done": "Letzte Abbuchung wurde rückgängig gemacht.",
        "usage_undo_none": "Keine rückgängig machbare Abbuchung gefunden.",
        "usage_applied": "Verbrauch wurde erfolgreich abgezogen.",
        "usage_preview": "Verbrauchsvorschau",
        "usage_detected_spools": "Automatisch erkannte Spulen",
        "usage_apply_now": "Jetzt anwenden",
        "usage_manual_needed": "Bitte manuell Gramm und Spulen auswählen.",
        "usage_manual_mode": "Manueller Modus",
        "usage_no_file": "Bitte zuerst eine 3MF-Datei auswählen.",
        "usage_active_spools": "Aktive Spulen",
        "usage_deduction": "Abzug (g)",
        "usage_save_manual": "Manuell speichern",
        "usage_save_auto": "Automatisch speichern",
        "usage_preview_ready": "Automatische Vorschau bereit.",
        "apply_usage": "Verbrauch anwenden",
        "import": "Importieren",
        "import_hint": "Erlaubt: CSV oder Excel mit Spalten: brand, material, color, weight_g, remaining_g, price, location.",
        "backup_title": "Backup / Restore",
        "backup_hint": "Exportiere oder importiere die komplette Datenbank.",
        "backup_hint_sqlite": "SQLite-Modus: Export/Import als .db-Datei.",
        "backup_hint_postgres": "PostgreSQL-Modus: Export/Import als .dump-Datei (Custom Format).",
        "backup_export": "Backup exportieren",
        "backup_create": "Backup anlegen",
        "backup_import": "Backup importieren",
        "backup_import_file": "Backup-Datei",
        "backup_import_done": "Backup wurde erfolgreich importiert.",
        "backup_create_done": "Backup wurde erstellt.",
        "backup_create_failed": "Backup konnte nicht erstellt werden.",
        "backup_invalid_file": "Ungültige Datei. Bitte eine SQLite-Backup-Datei (.db) hochladen.",
        "backup_invalid_file_postgres": "Ungültige Datei. Bitte eine PostgreSQL-Backup-Datei (.dump, Custom Format) hochladen.",
        "backup_import_failed": "Backup konnte nicht importiert werden.",
        "backup_import_failed_postgres": "PostgreSQL-Backup konnte nicht importiert werden.",
        "backup_export_failed_postgres": "PostgreSQL-Backup konnte nicht exportiert werden.",
        "backup_file_restore_done": "Backup wurde zurückgespielt.",
        "backup_file_restore_failed": "Backup konnte nicht zurückgespielt werden.",
        "backup_file_delete_done": "Backup wurde gelöscht.",
        "backup_file_delete_failed": "Backup konnte nicht gelöscht werden.",
        "backup_file_not_found": "Backup-Datei wurde nicht gefunden.",
        "backup_storage_unavailable": "Backup-Speicher ist nicht verfügbar.",
        "backup_tab_manual": "Manuell",
        "backup_tab_files": "Backups",
        "backup_tab_auto": "Automatik",
        "backup_files_title": "Verfügbare Backups",
        "backup_files_empty": "Noch keine Backups vorhanden.",
        "backup_file_name": "Datei",
        "backup_file_size": "Größe",
        "backup_file_modified": "Geändert",
        "backup_file_source": "Quelle",
        "backup_file_source_manual": "Manuell",
        "backup_file_source_auto": "Automatisch",
        "backup_download": "Download",
        "backup_restore_file": "Wiederherstellen",
        "backup_delete": "Löschen",
        "backup_auto_title": "Automatische Backups",
        "backup_auto_enabled": "Auto-Backups aktivieren",
        "backup_auto_interval_hours": "Intervall (Stunden)",
        "backup_auto_retention_days": "Aufbewahrung (Tage)",
        "backup_auto_last_run": "Letzter Lauf",
        "backup_auto_settings_saved": "Auto-Backup-Einstellungen wurden gespeichert.",
        "backup_auto_hint": "Automatische Backups werden bei eingehenden App-Requests geprüft und bei Fälligkeit erstellt.",
        "backup_storage_path": "Speicherpfad",
        "backup_sqlite_only": "Backup/Restore in der Oberfläche ist aktuell nur mit SQLite verfügbar. Für PostgreSQL nutze bitte pg_dump/pg_restore.",
        "backup_pg_tools_missing": "PostgreSQL-Backup erfordert pg_dump und pg_restore im App-Container.",
        "backup_unsupported": "Backup/Restore wird für diesen Datenbanktyp nicht unterstützt.",
        "backup_reset_title": "Alle Daten löschen",
        "backup_reset_hint": "Löscht alle Datenbank-Einträge unwiderruflich. Backup-Dateien im Backup-Speicher bleiben erhalten.",
        "backup_reset_confirm_checkbox": "Ich verstehe, dass alle Datenbank-Einträge gelöscht werden.",
        "backup_reset_confirm_phrase_label": "Bestätigungstext",
        "backup_reset_confirm_phrase_hint": "Bitte exakt eingeben: {phrase}",
        "backup_reset_confirm_phrase_placeholder": "Bestätigungstext eingeben",
        "backup_reset_action": "Alle Daten jetzt löschen",
        "backup_reset_create_backup": "Vor dem Löschen ein Backup erstellen",
        "backup_reset_backup_failed": "Löschen abgebrochen: Backup vor dem Löschen konnte nicht erstellt werden.",
        "backup_reset_confirm_required": "Löschen abgebrochen: Beide Bestätigungen sind erforderlich.",
        "backup_reset_done": "Alle Datenbank-Einträge wurden gelöscht ({rows}). Backup-Dateien wurden nicht verändert.",
        "backup_reset_done_with_backup": "Alle Datenbank-Einträge wurden gelöscht ({rows}). Vorher wurde ein Backup erstellt: {filename}",
        "backup_reset_failed": "Datenbank konnte nicht vollständig geleert werden.",
        "upload_too_large": "Datei ist zu groß. Maximum: {max_mb} MB.",
        "label_print": "Etikettendruck",
        "label_print_title": "Etikettendruck",
        "label_print_hint": "Wähle Spulen und ein Drucklayout (A4 oder Labelbogen).",
        "label_target": "Etikett-Typ",
        "label_target_spool": "Spulen",
        "label_target_location": "Lagerorte",
        "label_target_printer": "Drucker",
        "label_select_printers": "Drucker auswählen",
        "label_printer_none_selected": "Bitte mindestens einen Drucker auswählen.",
        "label_select_locations": "Lagerorte auswählen",
        "label_location_none_selected": "Bitte mindestens einen Lagerort auswählen.",
        "label_layout": "Layout",
        "label_custom_title": "Eigenes Label-Format",
        "label_custom_hint": "Eigenes Layout mit Spalten und Etikettgröße (mm) speichern.",
        "label_custom_name": "Name",
        "label_custom_columns": "Spalten",
        "label_custom_width": "Breite (mm)",
        "label_custom_height": "Höhe (mm)",
        "label_custom_columns_auto": "Spalten werden beim Generieren automatisch bestimmt.",
        "label_custom_add": "Format speichern",
        "label_custom_saved": "Eigenes Label-Format wurde gespeichert.",
        "label_custom_existing": "Gespeicherte Formate",
        "label_custom_deleted": "Eigenes Label-Format wurde gelöscht.",
        "label_custom_error_delete_builtin": "Standard-Layout kann nicht gelöscht werden.",
        "label_custom_error_name": "Bitte einen gültigen Namen angeben.",
        "label_custom_error_columns": "Spalten müssen zwischen 1 und 8 liegen.",
        "label_custom_error_size": "Breite und Höhe müssen größer als 0 sein.",
        "label_custom_error_exists": "Ein Label-Format mit diesem Namen existiert bereits.",
        "label_custom_error_delete_failed": "Eigenes Label-Format konnte nicht gelöscht werden.",
        "label_layout_a4": "A4 (Karten)",
        "label_layout_sheet": "Labelbogen (3×8)",
        "label_select_spools": "Spulen auswählen",
        "label_print_mode": "Druckmodus",
        "label_print_mode_sheet": "A4-Bogen",
        "label_print_mode_single": "Einzelnes Etikett (volle Größe)",
        "label_orientation": "Ausrichtung auf dem Etikett",
        "label_orientation_horizontal": "Horizontal",
        "label_orientation_vertical": "Vertikal",
        "label_content": "Inhalt",
        "label_field_spool_id": "Spulen-ID",
        "label_field_brand": "Marke",
        "label_field_material_color": "Material + Farbe",
        "label_field_weight": "Gewicht",
        "label_field_remaining": "Restmenge",
        "label_field_location": "Lagerort",
        "label_save_defaults": "Als Standard speichern",
        "label_defaults_saved": "Label-Einstellungen wurden als Standard gespeichert.",
        "label_generate": "Etiketten erzeugen",
        "label_none_selected": "Bitte mindestens eine Spule auswählen.",
        "label_print_now": "Drucken",
        "label_back": "Zurück",
        "qr_scan": "QR-Scan",
        "qr_scan_title": "QR-Scan (Etikett einlesen)",
        "qr_scan_hint": "Scanne den QR-Code, um Spuleninfos zu öffnen und den Status zu ändern.",
        "qr_scan_input": "QR-Inhalt",
        "qr_scan_lookup": "Spule laden",
        "qr_scan_start_camera": "Kamera starten",
        "qr_scan_stop_camera": "Kamera stoppen",
        "qr_scan_camera_unsupported": "Kamera-Scan wird auf diesem Gerät/Brower nicht unterstützt. Du kannst den QR-Inhalt manuell einfügen.",
        "qr_scan_camera_requires_https": "Kamera benötigt meist HTTPS (oder localhost). Nutze alternativ Bild-Upload.",
        "qr_scan_upload_image": "QR-Bild hochladen",
        "qr_scan_decode_image": "Bild einlesen",
        "qr_scan_image_no_qr": "Im Bild wurde kein QR-Code erkannt.",
        "qr_scan_invalid": "QR-Code konnte nicht gelesen werden.",
        "qr_scan_not_found": "Keine passende Spule gefunden.",
        "qr_scan_location_loaded": "Lagerort wurde geladen.",
        "qr_scan_printer_loaded": "Drucker wurde geladen.",
        "qr_scan_loaded": "Spule wurde geladen.",
        "qr_scan_status": "Status",
        "qr_scan_action_empty": "Als leer markieren",
        "qr_scan_action_in_use": "Als in Nutzung markieren",
        "qr_scan_action_idle": "Als nicht in Nutzung markieren",
        "qr_scan_lifecycle_label": "Lebenszyklus",
        "qr_scan_lifecycle_title": "Lebenszyklus",
        "qr_scan_lifecycle_hint": "Setze den Lebenszyklus direkt nach dem Scan.",
        "qr_scan_action_set_lifecycle": "Lebenszyklus speichern",
        "qr_scan_storage_title": "Lagerplatz",
        "qr_scan_storage_hint": "Setze den strukturierten Lagerplatz direkt nach dem Scan.",
        "qr_scan_storage_label": "Lagerort",
        "qr_scan_storage_save": "Lagerplatz speichern",
        "qr_scan_action_done_empty": "Spule wurde als leer markiert.",
        "qr_scan_action_done_in_use": "Spule wurde als in Nutzung markiert.",
        "qr_scan_action_done_idle": "Spule wurde als nicht in Nutzung markiert.",
        "qr_scan_action_done_lifecycle": "Lebenszyklus wurde aktualisiert.",
        "qr_scan_action_done_storage": "Lagerplatz wurde aktualisiert.",
        "qr_scan_mapping_title": "AMS-/Externe-Zuordnung",
        "qr_scan_mapping_hint": "Ordne die gescannte Spule einem AMS-Slot oder der externen Spule eines Druckers zu.",
        "qr_scan_mapping_target": "Ziel",
        "qr_scan_mapping_target_ams": "AMS-Slot",
        "qr_scan_mapping_target_external": "Externe Spule",
        "qr_scan_mapping_target_clear": "Zuordnung entfernen",
        "qr_scan_mapping_printer": "Drucker",
        "qr_scan_mapping_printer_placeholder": "Bitte wählen",
        "qr_scan_mapping_slot": "AMS-Slot",
        "qr_scan_mapping_save": "Zuordnung speichern",
        "qr_scan_action_done_mapping": "Zuordnung wurde aktualisiert.",
        "qr_scan_action_invalid_mapping": "Ungültige AMS-/Externe-Zuordnung.",
        "qr_scan_action_invalid_mapping_printer": "Bitte einen Drucker auswählen.",
        "qr_scan_action_mapping_conflict": "Zuordnungskonflikt: Ziel ist bereits einer anderen Spule zugeordnet.",
        "qr_scan_action_invalid_lifecycle": "Ungültiger Lebenszyklus-Status.",
        "qr_scan_action_invalid": "Unbekannte Aktion.",
        "qr_scan_manage_title": "Spulenstatus setzen",
        "qr_scan_manage_hint": "Setze den Status direkt nach dem Scan.",
        "qr_scan_back_to_scan": "Zurück zum Scanner",
        "qr_scan_auto_back": "Nach Aktion automatisch zurück zum Scanner",
        "qr_scan_next_ready": "Status gespeichert. Scanner ist bereit für die nächste Spule.",
    },
    "en": {
        "app_title": "Filament Database",
        "app_subtitle": "Track your filament spools",
        "footer_text": "Local filament management",
        "stats_title": "Statistics",
        "stat_total_spools": "Total spools",
        "stat_total_weight": "Total weight",
        "stat_total_remaining": "Remaining",
        "stat_total_value": "Inventory value",
        "stat_empty_spools": "Empty spools",
        "stat_low_stock_spools": "Low stock",
        "kpi_month_usage": "Monthly usage",
        "kpi_month_cost": "Cost (month)",
        "kpi_usage_trend": "Usage per month",
        "kpi_cost_trend": "Cost per month",
        "kpi_top_material_trend": "Top material per month",
        "kpi_top_color_trend": "Top color per month",
        "kpi_last_months": "last 6 months",
        "kpi_no_usage_data": "No usage data available.",
        "top5_materials": "Top 5 materials",
        "top5_colors": "Top 5 colors",
        "top5_remaining_share": "Remaining share",
        "settings": "Settings",
        "nav_booking": "Booking",
        "nav_tracking": "Tracking",
        "nav_slot_status": "Slot status",
        "nav_printers": "Printers",
        "nav_storage_locations": "Storage locations",
        "nav_supplies": "Supplies",
        "nav_menu": "Menu",
        "nav_home": "Dashboard",
        "settings_language": "Language",
        "settings_theme": "Theme",
        "settings_project": "Project",
        "settings_privacy_blur": "Privacy blur",
        "settings_privacy_blur_enable": "Enable blur",
        "settings_privacy_blur_disable": "Disable blur",
        "live_updated": "Live updated",
        "live_updated_now": "just now",
        "settings_auto_refresh": "Auto refresh",
        "auto_refresh_off": "Off",
        "auto_refresh_5s": "5 seconds",
        "auto_refresh_10s": "10 seconds",
        "auto_refresh_30s": "30 seconds",
        "project_private": "Private",
        "project_business": "Business",
        "theme_light": "Light",
        "theme_dark": "Dark",
        "theme_system": "System",
        "landing_title": "Welcome to Filament Database",
        "landing_subtitle": "Manage inventory, storage locations, and usage in one place.",
        "landing_auth_hint": "Authentication is prepared and can be connected to real user management in the next step.",
        "landing_cta_login": "Sign in",
        "landing_cta_register": "Register",
        "landing_cta_dashboard": "Open dashboard",
        "auth_email": "Email",
        "auth_password": "Password",
        "auth_name": "Name",
        "login_title": "Sign in",
        "login_hint": "Sign in with your account.",
        "register_title": "Register",
        "register_hint": "Create a new account.",
        "auth_submit_login": "Sign in",
        "auth_submit_register": "Create account",
        "auth_coming_soon": "Authentication scaffolding is in place. Backend integration follows in the next step.",
        "auth_logout": "Sign out",
        "auth_login_success": "Successfully signed in.",
        "auth_register_success": "Account created and signed in.",
        "auth_invalid_credentials": "Invalid email or password.",
        "auth_email_exists": "This email is already registered.",
        "auth_password_too_short": "Password must be at least 8 characters.",
        "auth_required": "Please sign in first.",
        "quick_actions": "Quick actions",
        "data_section": "Data",
        "backup_restore": "Backup / Restore",
        "analysis_tab": "Analysis",
        "audit_tab": "Audit log",
        "thresholds_tab": "Thresholds",
        "analysis_title": "Analysis",
        "audit_title": "Audit log",
        "thresholds_title": "Thresholds",
        "thresholds_hint": "Overview of all configured low-stock thresholds.",
        "thresholds_material_defaults": "Material default thresholds",
        "thresholds_spool_overrides": "Spool-specific thresholds",
        "thresholds_none_material": "No material thresholds set.",
        "thresholds_none_spool": "No spool thresholds set.",
        "analysis_hint": "Inventory grouped by brand, material, color, and location.",
        "analysis_by_brand": "By brand",
        "analysis_by_material": "By material",
        "analysis_by_color": "By color",
        "analysis_by_location": "By location",
        "analysis_count": "Count",
        "analysis_share": "Remaining share",
        "analysis_period_days": "Period (days)",
        "analysis_trend_months": "Trend (months)",
        "analysis_apply_filters": "Apply filters",
        "analysis_kpi_usage_period": "Usage in period",
        "analysis_kpi_cost_period": "Cost in period",
        "analysis_kpi_low_stock_count": "Low stock (current)",
        "analysis_kpi_top_material_usage": "Top usage by material",
        "analysis_kpi_top_color_usage": "Top usage by color",
        "analysis_kpi_printer_slot_usage": "Usage by printer/slot",
        "analysis_chart_usage_cost": "Usage & cost trend",
        "analysis_low_stock_items": "Critical spools",
        "analysis_no_data": "No data in the selected period.",
        "audit_hint": "Revision-safe history of critical actions (who/what/when).",
        "audit_action": "Action",
        "audit_period_days": "Period (days)",
        "audit_actor": "Actor",
        "audit_entity": "Entity",
        "audit_details": "Details",
        "audit_all_actions": "All actions",
        "audit_no_data": "No audit entries for the selected period.",
        "add_spool": "Add spool",
        "import_data": "Import",
        "import_export": "Import / Export",
        "export_csv": "Export CSV",
        "export_excel": "Export Excel",
        "spool_list": "Spool list",
        "search_placeholder": "Search brand, material, color, location",
        "hide_empty_spools": "Hide empty spools",
        "rows_per_page": "Rows per page",
        "entries_label": "entries",
        "page_label": "Page",
        "prev_page": "Previous",
        "next_page": "Next",
        "all_colors": "All colors",
        "search": "Search",
        "spool_index": "Index",
        "brand": "Brand",
        "material": "Material",
        "color": "Color",
        "bulk_add": "Bulk add",
        "bulk_add_hint": "Create multiple spools in one step.",
        "add_row": "Add row",
        "save_all": "Save all",
        "quantity": "Quantity",
        "quantity_hint": "Creates multiple identical spools.",
        "manage_presets": "Manage presets",
        "presets_title": "Presets",
        "add_brand": "Add brand",
        "add_material": "Add material",
        "add_color": "Add color",
        "add_color_map": "Assign colors",
        "presets_basic_title": "Add basics",
        "presets_basic_hint": "Quickly add brands, materials, or colors.",
        "assign_colors_title": "Assign colors",
        "assign_colors_hint": "Choose brand and material, then add colors (comma-separated).",
        "import_colors": "Import colors",
        "import_colors_hint": "CSV/Excel with columns: brand, material, color",
        "select_brand": "Select brand",
        "select_material": "Select material",
        "colors_list": "Colors (comma-separated)",
        "brand_hint": "Separate multiple brands with commas",
        "material_hint": "Separate multiple materials with commas",
        "color_hint": "Separate multiple colors with commas",
        "material_group": "Material group",
        "weight": "Weight",
        "remaining": "Remaining",
        "threshold": "Threshold",
        "price": "Price",
        "location": "Location",
        "storage_location": "Structured location",
        "storage_location_none": "No structured location",
        "storage_locations_title": "Storage locations",
        "storage_locations_hint": "Manage storage areas and bins (e.g. RACK1/BIN_A).",
        "storage_locations_add": "Add storage location",
        "storage_area_code": "Area code",
        "storage_area_name": "Area name",
        "storage_sub_code": "Bin code",
        "storage_sub_name": "Bin name",
        "storage_path": "Path",
        "storage_usage": "Assigned spools",
        "storage_delete": "Delete location",
        "storage_none": "No storage locations available.",
        "storage_invalid_code": "Invalid code. Allowed: letters/numbers plus - and _.",
        "storage_location_exists": "This storage location already exists.",
        "storage_location_saved": "Storage location was saved.",
        "storage_location_deleted": "Storage location was deleted.",
        "storage_location_in_use": "Storage location is still assigned to spools and cannot be deleted.",
        "storage_location_invalid": "Selected storage location is invalid.",
        "storage_filter": "Location filter",
        "storage_filter_all": "All locations",
        "supplies_title": "Supplies",
        "supplies_hint": "Simple inventory for consumables like glue, nozzles, or cleaning material.",
        "supplies_add": "Add item",
        "supplies_category_add": "Add category",
        "supplies_category_exists": "Category already exists.",
        "supplies_category_saved": "Category saved.",
        "supplies_name": "Name",
        "supplies_category": "Category",
        "supplies_quantity": "Quantity",
        "supplies_unit": "Unit",
        "supplies_min_quantity": "Minimum stock",
        "supplies_notes": "Notes",
        "supplies_adjust": "Adjust",
        "supplies_adjust_hint": "Enter value with + or -, e.g. -1 or +2.",
        "supplies_none": "No supplies yet.",
        "supplies_category_none": "No category",
        "supplies_saved": "Item saved.",
        "supplies_updated": "Item updated.",
        "supplies_deleted": "Item deleted.",
        "supplies_adjusted": "Stock was adjusted.",
        "supplies_invalid": "Please provide a name and valid quantity.",
        "supplies_invalid_adjust": "Please provide a valid adjustment value.",
        "supplies_default_category": "Consumables",
        "supplies_default_unit": "pcs",
        "ams_printer": "AMS printer",
        "ams_slot": "AMS slot",
        "status": "Status",
        "lifecycle_status": "Lifecycle",
        "lifecycle_filter_all": "All lifecycle statuses",
        "lifecycle_new": "New",
        "lifecycle_opened": "Opened",
        "lifecycle_dry_stored": "Dry stored",
        "lifecycle_humidity_risk": "Humidity risk",
        "lifecycle_drying": "Drying",
        "lifecycle_brittle": "Brittle",
        "lifecycle_empty": "Empty",
        "lifecycle_recycled": "Recycled",
        "lifecycle_archived": "Archived",
        "actions": "Actions",
        "in_use": "In use",
        "empty": "Empty",
        "low_stock": "Low stock",
        "idle": "Idle",
        "threshold_source_spool": "Spool",
        "threshold_source_material": "Material",
        "threshold_none": "-",
        "low_stock_threshold": "Low-stock threshold",
        "material_thresholds_title": "Material thresholds",
        "material_thresholds_hint": "Default per-spool threshold by material in grams.",
        "material_total_threshold": "Material total threshold",
        "material_total_thresholds_title": "Material total thresholds",
        "material_total_thresholds_hint": "Threshold on total inventory per material in grams.",
        "reorder_list_title": "Reorder needed",
        "reorder_none": "No reorder needed right now.",
        "reorder_missing": "Missing",
        "reorder_min_order": "Min order",
        "reorder_critical_only": "Critical entries only",
        "reorder_show_all": "Show all entries",
        "reorder_needed": "Reorder",
        "reorder_ok": "OK",
        "forecast_card_30": "Inventory runway (30-day usage)",
        "forecast_card_90": "Inventory runway (90-day usage)",
        "forecast_days": "days",
        "forecast_daily_usage": "Avg usage/day",
        "forecast_no_data": "No usage data",
        "import_profile_use": "Use import mapping profile",
        "import_profile_none": "No profile",
        "import_profile_save_as": "Save mapping as profile",
        "import_map_brand": "Column for brand",
        "import_map_material": "Column for material",
        "import_map_color": "Column for color",
        "import_map_weight": "Column for weight (g)",
        "import_map_remaining": "Column for remaining (g)",
        "import_map_threshold": "Column for low-stock threshold",
        "import_map_price": "Column for price",
        "import_map_location": "Column for location",
        "toggle_use": "Toggle",
        "edit": "Edit",
        "delete": "Delete",
        "qr": "QR",
        "confirm_delete": "Delete this spool?",
        "no_spools": "No spools found.",
        "save": "Save",
        "cancel": "Cancel",
        "usage_upload": "Booking",
        "booking_area_title": "Booking",
        "booking_section_book": "Book",
        "booking_section_tracking": "Tracking",
        "usage_hint": "Upload a 3MF file. If grams are missing, enter them manually.",
        "select_spools": "Select spools",
        "upload_3mf": "3MF file",
        "manual_grams": "Manual grams",
        "manual_grams_hint": "Only needed if the 3MF has no grams metadata.",
        "usage_no_grams": "No gram value was found in the 3MF. Please enter it manually.",
        "usage_no_grams_bambu_unsliced": "This Bambu 3MF does not contain usage data (likely not sliced). Slice in Bambu Studio and save again, or enter values manually.",
        "usage_no_match": "No matching spool was auto-detected. Please select one manually.",
        "usage_breakdown": "Detected material usage",
        "usage_total": "Total",
        "usage_total_length": "Total length",
        "usage_filament_switches": "Filament switches",
        "usage_estimated_cost": "Cost",
        "usage_advanced_title": "Advanced Bambu statistics",
        "usage_history_title": "Usage history",
        "usage_history_when": "When",
        "usage_history_who": "Who",
        "usage_history_slicer": "Slicer",
        "usage_history_mode": "Mode",
        "usage_mode_auto": "Automatic",
        "usage_mode_manual": "Manual",
        "usage_mode_auto_slicer": "Automatic (Slicer)",
        "usage_mode_auto_bambu": "Automatic (Bambu Studio)",
        "usage_mode_upload_manual": "File upload (manual)",
        "usage_mode_manual_entry": "Manual entry",
        "usage_history_file": "3MF file",
        "usage_history_spool": "Spool",
        "usage_history_spools": "Spools",
        "usage_history_breakdown": "Breakdown",
        "usage_history_spool_id": "Spool index",
        "usage_history_amount": "Deduction",
        "usage_history_printer": "Printer",
        "usage_history_ams_slots": "AMS slots",
        "ams_slot_conflict": "AMS slot conflict: this slot is already assigned to another spool.",
        "slot_status_title": "Expected/Live slot status",
        "slot_status_hint": "Compares configured spool mapping with the latest polled device state.",
        "slot_status_printer": "Printer",
        "slot_status_slot": "Slot",
        "slot_status_ams": "AMS",
        "slot_status_expected": "Expected (spool)",
        "slot_status_observed": "Live",
        "slot_status_state": "State",
        "slot_status_seen": "Last seen",
        "slot_status_source": "Source",
        "slot_state_ok": "OK",
        "slot_state_mismatch": "Mismatch",
        "slot_state_missing": "Missing",
        "slot_state_stale": "Stale",
        "slot_state_unknown": "Unknown",
        "slot_status_no_mapped": "No mapped slots found.",
        "slot_status_no_live": "No live slot data available.",
        "slot_data_health": "Live data status",
        "slot_data_fresh": "Current",
        "slot_data_stale": "Stale",
        "slot_data_no_data": "No live data",
        "slot_data_age": "Age",
        "slot_remap_action": "Fix AMS mapping from live data",
        "slot_remap_done": "AMS mapping updated: {updated} spool(s).",
        "slot_remap_none": "No unambiguous corrections found.",
        "slot_remap_no_live": "No live slot data available.",
        "slot_format_migrate_action": "Migrate slot format to 1xx/2xx",
        "slot_format_migrate_done": "Slot format migrated: spools={spools}, live slots={states}, history contexts={contexts}.",
        "slot_format_migrate_skip": "Some entries were skipped because of conflicts: {count}.",
        "printers_title": "Printer management",
        "printers_hint": "Manage multiple printers and their live telemetry in one place.",
        "printers_add": "Add printer",
        "printers_none": "No printers configured.",
        "printer_name": "Name",
        "printer_serial": "Serial",
        "printer_host": "Host/IP",
        "printer_port": "Port",
        "printer_access_code": "Access code",
        "printer_ams_name_map": "AMS name",
        "printer_ams_name_map_hint": "e.g. HT-A",
        "printer_active": "Active",
        "printer_status": "Status",
        "printer_last_seen": "Last seen",
        "printer_job": "Job",
        "printer_progress": "Progress",
        "printer_temps": "Temperatures",
        "printer_firmware": "Firmware",
        "printer_source": "Source",
        "printer_error": "Error",
        "printer_external_spool": "External spool",
        "printer_external_spool_active": "Active",
        "printer_external_spool_inactive": "Inactive",
        "printer_tab_device": "Printer data",
        "printer_tab_ams": "AMS data",
        "printer_ams_title": "AMS (live slots)",
        "printer_ams_empty": "No AMS live data for this printer.",
        "printer_saved": "Printer saved.",
        "printer_deleted": "Printer deleted.",
        "printer_invalid": "Please provide name and serial.",
        "printer_duplicate_serial": "This serial already exists in this project.",
        "printer_duplicate_name": "This printer name already exists in this project.",
        "printer_status_online": "Online",
        "printer_status_offline": "Offline",
        "printer_status_unknown": "Unknown",
        "usage_history_empty": "No usage entries yet.",
        "usage_undo_last": "Undo last deduction",
        "usage_undo_done": "Last deduction was undone.",
        "usage_undo_none": "No undoable deduction found.",
        "usage_applied": "Usage was successfully deducted.",
        "usage_preview": "Usage preview",
        "usage_detected_spools": "Auto-detected spools",
        "usage_apply_now": "Apply now",
        "usage_manual_needed": "Please choose grams and spools manually.",
        "usage_manual_mode": "Manual mode",
        "usage_no_file": "Please select a 3MF file first.",
        "usage_active_spools": "Active spools",
        "usage_deduction": "Deduction (g)",
        "usage_save_manual": "Save manual",
        "usage_save_auto": "Save automatic",
        "usage_preview_ready": "Automatic preview is ready.",
        "apply_usage": "Apply usage",
        "import": "Import",
        "import_hint": "Allowed: CSV or Excel with columns: brand, material, color, weight_g, remaining_g, price, location.",
        "backup_title": "Backup / Restore",
        "backup_hint": "Export or import the complete database.",
        "backup_hint_sqlite": "SQLite mode: export/import as a .db file.",
        "backup_hint_postgres": "PostgreSQL mode: export/import as a .dump file (custom format).",
        "backup_export": "Export backup",
        "backup_create": "Create backup",
        "backup_import": "Import backup",
        "backup_import_file": "Backup file",
        "backup_import_done": "Backup imported successfully.",
        "backup_create_done": "Backup created successfully.",
        "backup_create_failed": "Backup could not be created.",
        "backup_invalid_file": "Invalid file. Please upload an SQLite backup file (.db).",
        "backup_invalid_file_postgres": "Invalid file. Please upload a PostgreSQL backup file (.dump, custom format).",
        "backup_import_failed": "Backup could not be imported.",
        "backup_import_failed_postgres": "PostgreSQL backup could not be imported.",
        "backup_export_failed_postgres": "PostgreSQL backup could not be exported.",
        "backup_file_restore_done": "Backup restored successfully.",
        "backup_file_restore_failed": "Backup could not be restored.",
        "backup_file_delete_done": "Backup deleted.",
        "backup_file_delete_failed": "Backup could not be deleted.",
        "backup_file_not_found": "Backup file was not found.",
        "backup_storage_unavailable": "Backup storage is unavailable.",
        "backup_tab_manual": "Manual",
        "backup_tab_files": "Backups",
        "backup_tab_auto": "Automatic",
        "backup_files_title": "Available backups",
        "backup_files_empty": "No backups yet.",
        "backup_file_name": "File",
        "backup_file_size": "Size",
        "backup_file_modified": "Modified",
        "backup_file_source": "Source",
        "backup_file_source_manual": "Manual",
        "backup_file_source_auto": "Automatic",
        "backup_download": "Download",
        "backup_restore_file": "Restore",
        "backup_delete": "Delete",
        "backup_auto_title": "Automatic backups",
        "backup_auto_enabled": "Enable automatic backups",
        "backup_auto_interval_hours": "Interval (hours)",
        "backup_auto_retention_days": "Retention (days)",
        "backup_auto_last_run": "Last run",
        "backup_auto_settings_saved": "Automatic backup settings saved.",
        "backup_auto_hint": "Automatic backups are checked on incoming app requests and created when due.",
        "backup_storage_path": "Storage path",
        "backup_sqlite_only": "In-app backup/restore is currently available for SQLite only. For PostgreSQL, use pg_dump/pg_restore.",
        "backup_pg_tools_missing": "PostgreSQL backup requires pg_dump and pg_restore in the app container.",
        "backup_unsupported": "Backup/restore is not supported for this database type.",
        "backup_reset_title": "Delete all data",
        "backup_reset_hint": "Irreversibly deletes all database records. Backup files in backup storage remain untouched.",
        "backup_reset_confirm_checkbox": "I understand that all database records will be deleted.",
        "backup_reset_confirm_phrase_label": "Confirmation text",
        "backup_reset_confirm_phrase_hint": "Please type exactly: {phrase}",
        "backup_reset_confirm_phrase_placeholder": "Enter confirmation text",
        "backup_reset_action": "Delete all data now",
        "backup_reset_create_backup": "Create a backup before deleting",
        "backup_reset_backup_failed": "Deletion aborted: pre-delete backup could not be created.",
        "backup_reset_confirm_required": "Deletion aborted: both confirmations are required.",
        "backup_reset_done": "All database records were deleted ({rows}). Backup files were not changed.",
        "backup_reset_done_with_backup": "All database records were deleted ({rows}). A backup was created first: {filename}",
        "backup_reset_failed": "Database could not be fully cleared.",
        "upload_too_large": "File is too large. Maximum: {max_mb} MB.",
        "label_print": "Label printing",
        "label_print_title": "Label printing",
        "label_print_hint": "Select spools and a print layout (A4 or label sheet).",
        "label_target": "Label target",
        "label_target_spool": "Spools",
        "label_target_location": "Storage locations",
        "label_target_printer": "Printers",
        "label_select_printers": "Select printers",
        "label_printer_none_selected": "Please select at least one printer.",
        "label_select_locations": "Select storage locations",
        "label_location_none_selected": "Please select at least one storage location.",
        "label_layout": "Layout",
        "label_custom_title": "Custom label format",
        "label_custom_hint": "Save your own layout with columns and label size (mm).",
        "label_custom_name": "Name",
        "label_custom_columns": "Columns",
        "label_custom_width": "Width (mm)",
        "label_custom_height": "Height (mm)",
        "label_custom_columns_auto": "Columns are determined automatically when generating labels.",
        "label_custom_add": "Save format",
        "label_custom_saved": "Custom label format was saved.",
        "label_custom_existing": "Saved formats",
        "label_custom_deleted": "Custom label format was deleted.",
        "label_custom_error_delete_builtin": "Built-in layout cannot be deleted.",
        "label_custom_error_name": "Please enter a valid name.",
        "label_custom_error_columns": "Columns must be between 1 and 8.",
        "label_custom_error_size": "Width and height must be greater than 0.",
        "label_custom_error_exists": "A label format with this name already exists.",
        "label_custom_error_delete_failed": "Custom label format could not be deleted.",
        "label_layout_a4": "A4 (cards)",
        "label_layout_sheet": "Label sheet (3×8)",
        "label_select_spools": "Select spools",
        "label_print_mode": "Print mode",
        "label_print_mode_sheet": "A4 sheet",
        "label_print_mode_single": "Single label (full size)",
        "label_orientation": "Orientation on label",
        "label_orientation_horizontal": "Horizontal",
        "label_orientation_vertical": "Vertical",
        "label_content": "Content",
        "label_field_spool_id": "Spool ID",
        "label_field_brand": "Brand",
        "label_field_material_color": "Material + color",
        "label_field_weight": "Weight",
        "label_field_remaining": "Remaining",
        "label_field_location": "Location",
        "label_save_defaults": "Save as default",
        "label_defaults_saved": "Label preferences were saved as default.",
        "label_generate": "Generate labels",
        "label_none_selected": "Please select at least one spool.",
        "label_print_now": "Print",
        "label_back": "Back",
        "qr_scan": "QR scan",
        "qr_scan_title": "QR scan (read label)",
        "qr_scan_hint": "Scan the QR code to open spool details and update status.",
        "qr_scan_input": "QR payload",
        "qr_scan_lookup": "Load spool",
        "qr_scan_start_camera": "Start camera",
        "qr_scan_stop_camera": "Stop camera",
        "qr_scan_camera_unsupported": "Camera scanning is not supported on this device/browser. You can paste the QR payload manually.",
        "qr_scan_camera_requires_https": "Camera access usually requires HTTPS (or localhost). Use image upload as fallback.",
        "qr_scan_upload_image": "Upload QR image",
        "qr_scan_decode_image": "Read image",
        "qr_scan_image_no_qr": "No QR code detected in image.",
        "qr_scan_invalid": "Could not parse QR code.",
        "qr_scan_not_found": "No matching spool found.",
        "qr_scan_location_loaded": "Storage location loaded.",
        "qr_scan_printer_loaded": "Printer loaded.",
        "qr_scan_loaded": "Spool loaded.",
        "qr_scan_status": "Status",
        "qr_scan_action_empty": "Mark as empty",
        "qr_scan_action_in_use": "Mark as in use",
        "qr_scan_action_idle": "Mark as not in use",
        "qr_scan_lifecycle_label": "Lifecycle",
        "qr_scan_lifecycle_title": "Lifecycle",
        "qr_scan_lifecycle_hint": "Set the lifecycle directly after scanning.",
        "qr_scan_action_set_lifecycle": "Save lifecycle",
        "qr_scan_storage_title": "Storage",
        "qr_scan_storage_hint": "Set the structured storage location directly after scanning.",
        "qr_scan_storage_label": "Storage location",
        "qr_scan_storage_save": "Save storage",
        "qr_scan_action_done_empty": "Spool marked as empty.",
        "qr_scan_action_done_in_use": "Spool marked as in use.",
        "qr_scan_action_done_idle": "Spool marked as not in use.",
        "qr_scan_action_done_lifecycle": "Lifecycle was updated.",
        "qr_scan_action_done_storage": "Storage location was updated.",
        "qr_scan_mapping_title": "AMS/external assignment",
        "qr_scan_mapping_hint": "Assign the scanned spool to an AMS slot or to a printer's external spool.",
        "qr_scan_mapping_target": "Target",
        "qr_scan_mapping_target_ams": "AMS slot",
        "qr_scan_mapping_target_external": "External spool",
        "qr_scan_mapping_target_clear": "Remove assignment",
        "qr_scan_mapping_printer": "Printer",
        "qr_scan_mapping_printer_placeholder": "Please choose",
        "qr_scan_mapping_slot": "AMS slot",
        "qr_scan_mapping_save": "Save assignment",
        "qr_scan_action_done_mapping": "Assignment was updated.",
        "qr_scan_action_invalid_mapping": "Invalid AMS/external assignment.",
        "qr_scan_action_invalid_mapping_printer": "Please select a printer.",
        "qr_scan_action_mapping_conflict": "Assignment conflict: target is already assigned to another spool.",
        "qr_scan_action_invalid_lifecycle": "Invalid lifecycle status.",
        "qr_scan_action_invalid": "Unknown action.",
        "qr_scan_manage_title": "Set spool status",
        "qr_scan_manage_hint": "Adjust status directly after scanning.",
        "qr_scan_back_to_scan": "Back to scanner",
        "qr_scan_auto_back": "Automatically return to scanner after action",
        "qr_scan_next_ready": "Status saved. Scanner is ready for the next spool.",
    },
}


